name: IP Check Action test
on:
  workflow_dispatch:
    inputs:
      mode:
        description: single or bulk
        default: single
      ip:
        description: single IP (if mode=single)
        default: 8.8.8.8
      ips:
        description: List of IPs, comma separated, 200 max (if mode=bulk)
        default: 8.8.8.8,1.1.1.1
      fields:
        description: optional fields like (ip,country,city,asn,proxy,vpn,tor,hosting,threat) could be none (for all of them) or one or any
        default: ''

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run IP Check (single)
        if: ${{ github.event.inputs.mode == 'single' }}
        id: ipchk_single
        uses: ipcheckio/ip-check-action@v1   # or copy the "Use latest version" line from your Marketplace page
        with:
          ip: ${{ github.event.inputs.ip }}
          fields: ${{ github.event.inputs.fields }}
          api-key: ${{ secrets.IPCHECK_API_KEY }}

      - name: Run IP Check (bulk)
        if: ${{ github.event.inputs.mode == 'bulk' }}
        id: ipchk_bulk
        uses: ipcheckio/ip-check-action@v1
        with:
          ips: ${{ github.event.inputs.ips }}
          fields: ${{ github.event.inputs.fields }}
          api-key: ${{ secrets.IPCHECK_API_KEY }}

      - name: Show outputs
        run: |
          echo "Single summary:  ${{ steps.ipchk_single.outputs.summary }}"
          echo "Bulk summary:    ${{ steps.ipchk_bulk.outputs.summary }}"
          echo '${{ steps.ipchk_single.outputs.json || steps.ipchk_bulk.outputs.json }}' > result.json
          wc -c result.json
      - name: Upload result.json
        uses: actions/upload-artifact@v4
        with:
          name: ip-check-result
          path: result.json
